name: gda
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - anyio==4.11.0
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.3.0
      - dill==0.4.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.5
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.4.1
      - pyarrow==22.0.0
      - pyparsing==3.2.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.9.0+cu126
      - torchvision==0.24.0+cu126
      - tqdm==4.67.1
      - triton==3.5.0
      - typer-slim==0.20.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /root/miniconda3/envs/gda
